### Random Package

In [1]:
using Pkg
Pkg.add("Random")

   Resolving package versions...
    Updating `C:\Users\paulo\.julia\environments\v1.11\Project.toml`
  [9a3f8284] + Random v1.11.0
  No Changes to `C:\Users\paulo\.julia\environments\v1.11\Manifest.toml`


In [2]:
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg C:\Users\paulo\AppData\Local\Programs\Julia-1.11.4\share\julia\stdlib\v1.11\Pkg\src\Pkg.jl:787


Dict{String, VersionNumber} with 4 entries:
  "Statistics" => v"1.11.1"
  "IJulia"     => v"1.26.0"
  "Plots"      => v"1.40.11"
  "Random"     => v"1.11.0"

In [14]:
using Random
X1 = rand(3,4)   # 3x4 matrix with uniformly distributed data
X2 = randn(3,4)  # 3x4 matrix with normally distributed data

3×4 Matrix{Float64}:
 -0.497439  -0.80921  1.34903   -0.41968
 -1.99199    2.33456  0.294397  -0.166481
  0.665828  -1.88404  1.67542   -0.976091

### Algebra Operations

In [19]:
A = ones(3,5)
B = zeros(3,5)
C = zeros(2,3,2)   # tensor concept!

2×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0

In [20]:
using Pkg
Pkg.installed()

┌ Warning: Pkg.installed() is deprecated
└ @ Pkg C:\Users\paulo\AppData\Local\Programs\Julia-1.11.4\share\julia\stdlib\v1.11\Pkg\src\Pkg.jl:787


Dict{String, VersionNumber} with 4 entries:
  "Statistics" => v"1.11.1"
  "IJulia"     => v"1.26.0"
  "Plots"      => v"1.40.11"
  "Random"     => v"1.11.0"

In [21]:
Pkg.add("LinearAlgebra")
Pkg.installed()

   Resolving package versions...
    Updating `C:\Users\paulo\.julia\environments\v1.11\Project.toml`
  [37e2e46d] + LinearAlgebra v1.11.0
  No Changes to `C:\Users\paulo\.julia\environments\v1.11\Manifest.toml`
┌ Warning: Pkg.installed() is deprecated
└ @ Pkg C:\Users\paulo\AppData\Local\Programs\Julia-1.11.4\share\julia\stdlib\v1.11\Pkg\src\Pkg.jl:787


Dict{String, VersionNumber} with 5 entries:
  "Statistics"    => v"1.11.1"
  "LinearAlgebra" => v"1.11.0"
  "IJulia"        => v"1.26.0"
  "Plots"         => v"1.40.11"
  "Random"        => v"1.11.0"

In [22]:
using LinearAlgebra

In [24]:
# Identity matrix
A = I(10)

10×10 Diagonal{Bool, Vector{Bool}}:
 1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1  ⋅
 ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  ⋅  1

In [28]:
M = [2 4 5; 1 2 3; 6 7 0]

3×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0

In [29]:
typeof(M)

Matrix{Int64} (alias for Array{Int64, 2})

In [30]:
size(M)

(3, 3)

In [33]:
M[1,:]
M[:,1]

3-element Vector{Int64}:
 2
 1
 6

In [36]:
M = [2 4 5; 1 2 3; 6 7 0]
N = [1 2 3; 4 5 6; 7 8 9]

# Matrix concatenation
C = [M N]
C = [M; N]

6×3 Matrix{Int64}:
 2  4  5
 1  2  3
 6  7  0
 1  2  3
 4  5  6
 7  8  9

In [51]:
# Linear algebra operations
M
transpose(M)
tr(M)
det(M)
inv(M)
M*inv(M)
UpperTriangular(M)
LowerTriangular(M)
eigvecs(M)
eigvals(M)

3-element Vector{Float64}:
 -5.352954259951673
 -0.09882411688237432
  9.451778376834048